import bcrypt from 'bcryptjs';

const users = [
  {
    id: 1,
    email: 'quickcredit2019@gmail.com',
    firstName: 'Quick',
    lastName: 'Credit',
    password: bcrypt.hashSync('quickcredit2019', 10),
    address: 'No. 123, Acme Drive, Wakanda District',
    workAddress: 'No. 456, Foobar Avenue, Vibranium Valley',
    status: 'verified',
    isAdmin: true,
  },
  {
    id: 2,
    email: 'johndoe25@gmail.com',
    firstName: 'John',
    lastName: 'Doe',
    password: bcrypt.hashSync('johndoe25', 10),
    address: 'No. 123, Acme Drive, Wakanda District',
    workAddress: 'No. 456, Foobar Avenue, Vibranium Valley',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 3,
    email: 'janedoe25@gmail.com',
    firstName: 'Jane',
    lastName: 'Doe',
    password: bcrypt.hashSync('janedoe25', 10),
    address: 'No. 123, Acme Drive, Wakanda District',
    workAddress: 'No. 456, Foobar Avenue, Vibranium Valley',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 4,
    email: 'nikobellic25@gmail.com',
    firstName: 'Niko',
    lastName: 'Bellic',
    password: bcrypt.hashSync('nikobellic25', 10),
    address: 'No. 123, Acme Drive, Wakanda District',
    workAddress: 'No. 456, Foobar Avenue, Vibranium Valley',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 5,
    email: 'hansolo25@gmail.com',
    firstName: 'Han',
    lastName: 'Solo',
    password: bcrypt.hashSync('hansolo25', 10),
    address: 'No. 123, Acme Drive, Wakanda District',
    workAddress: 'No. 456, Foobar Avenue, Vibranium Valley',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 6,
    email: 'carljohnson25@gmail.com',
    firstName: 'Carl',
    lastName: 'Johnson',
    password: bcrypt.hashSync('carljohnson25', 10),
    address: 'No. 123, Acme Drive, Wakanda District',
    workAddress: 'No. 456, Foobar Avenue, Vibranium Valley',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 6,
    email: 'tommyvercetti25@gmail.com',
    firstName: 'Tommy',
    lastName: 'Vercetti',
    password: bcrypt.hashSync('tommyvercetti25', 10),
    address: 'No. 123, Acme Drive, Wakanda District',
    workAddress: 'No. 456, Foobar Avenue, Vibranium Valley',
    status: 'verified',
    isAdmin: false,
  },
];

export default users;
