const users = [
  {
    id: 1,
    email: 'quickcredit2019@gmail.com',
    firstName: 'Quick',
    lastName: 'Credit',
    password: 'quickcredit2019',
    address: 'No. 123, Acme Drive, Wakanda District',
    workAddress: 'No. 456, Foobar Avenue, Vibranium Valley',
    status: 'verified',
    isAdmin: true,
  },
  {
    id: 2,
    email: 'johndoe25@gmail.com',
    firstName: 'John',
    lastName: 'Doe',
    password: 'johndoe25',
    address: 'No. 123, Acme Drive, Wakanda District',
    workAddress: 'No. 456, Foobar Avenue, Vibranium Valley',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 3,
    email: 'janedoe25@gmail.com',
    firstName: 'Jane',
    lastName: 'Doe',
    password: 'janedoe25',
    address: 'No. 123, Acme Drive, Wakanda District',
    workAddress: 'No. 456, Foobar Avenue, Vibranium Valley',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 4,
    email: 'nikobellic25@gmail.com',
    firstName: 'Niko',
    lastName: 'Bellic',
    password: 'nikobellic25',
    address: 'No. 123, Acme Drive, Wakanda District',
    workAddress: 'No. 456, Foobar Avenue, Vibranium Valley',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 5,
    email: 'hansolo25@gmail.com',
    firstName: 'Han',
    lastName: 'Solo',
    password: 'hansolo25',
    address: 'No. 123, Acme Drive, Wakanda District',
    workAddress: 'No. 456, Foobar Avenue, Vibranium Valley',
    status: 'unverified',
    isAdmin: false,
  },
];

export default users;
